/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package web_app_basic;

/**
 * 1. client request는 main thread가 처리
 * 2. client request가 올때마다 thread 생성 후 request처리
 * 3. thread pool 적용
 */

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
